DWAPlannerROS:
  max_vel_trans: 0.3
  min_vel_trans: 0.1
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_y: 0.3
  min_vel_y: 0.1
  max_rot_vel: 0.3
  min_rot_vel: 0.1
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  acc_lim_theta: 5
  acc_lim_trans: 2.0
  prune_plan: false

  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.8
  trans_stopped_vel: 0.1
  rot_stopped_vel: 0.1
  sim_time: 4.0
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  

  #pdist_scale: 2
  occdist_scale: 0.2
  twirling_scale: 0.0
  stop_time_buffer: 0.5
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
  forward_point_distance: 0.3
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40

  use_dwa: true
  restore_defaults: False
  
  global_frame_id: odom
  meter_scoring: true
